routes/web.php
<?php

use App\Http\Controllers\ProvinceController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\VaccineCardController;
use App\Http\Controllers\VisitorController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
   return view('welcome');
});
Route::resource('provinces', ProvinceController::class);
Route::resource('visitors', VisitorController::class);
Route::resource('vaccine-cards', VaccineCardController::class);
Route::get('/report', [ReportController::class, 'index'])->name('report.index');
Route::get('reports/export', [ReportController::class, 'export'])->name('report.export');

app/Models/Province.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Province extends Model
{
    use HasFactory;
    protected $table = 'provinces';
    protected $fillable = ['name'];

    public function visitors()
    {
        return $this->hasMany(Visitor::class);
    }
}

app/Http/Controllers/ProvinceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Province;
use Illuminate\Http\Request;

class ProvinceController extends Controller
{
    public function index () 
    {
        $provinces = Province::all();
        // dd($provinces);
        return view('provinces.index', compact('provinces'));
    }
    public function create()
    {
        return view('provinces.create');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|string|max:255',
        ]);

        Province::create($request->all());
        return redirect()->route('provinces.index')
                         ->with('success', 'Province created successfully.');
    }

    public function edit(Province $province)
    {
        return view('provinces.edit', compact('province'));
    }

    public function update(Request $request, Province $province)
    {
        $request->validate([
            'name' => 'required|string|max:255',
        ]);

        $province->update($request->all());
        return redirect()->route('provinces.index')
                         ->with('success', 'Province updated successfully.');
    }

    public function destroy(Province $province)
    {
        $province->delete();
        return redirect()->route('provinces.index')
                         ->with('success', 'Province deleted successfully.');
    }
}

resources/views/provinces/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h2>Add Province</h2>
    <form action="{{ route('provinces.store') }}" method="POST">
        @csrf
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" name="name" id="name" class="form-control" required>
        </div>
        <button type="submit" class="btn btn-primary">Add Province</button>
    </form>
</div>
@endsection

resources/views/provinces/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h2>Edit Province</h2>
    <form action="{{ route('provinces.update', $province->id) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" name="name" id="name" class="form-control" value="{{ $province->name }}" required>
        </div>
        <button type="submit" class="btn btn-primary">Update Province</button>
    </form>
</div>
@endsection

resources/views/provinces/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h2>Provinces</h2>
    @if (session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif
    <a href="{{ route('provinces.create') }}" class="btn btn-primary mb-3">Add Province</a>
    <table class="table">
        <thead>
            <tr>
                <th>No</th>
                <th>Name</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach($provinces as $index => $province)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $province->name }}</td>
                    <td>
                        <a href="{{ route('provinces.edit', $province->id) }}" class="btn btn-warning btn-sm">Edit</a>
                        <form action="{{ route('provinces.destroy', $province->id) }}" method="POST" style="display:inline-block;">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?')">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endsection