routes/web.php
<?php

use App\Http\Controllers\ProvinceController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\VaccineCardController;
use App\Http\Controllers\VisitorController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
   return view('welcome');
});
Route::resource('provinces', ProvinceController::class);
Route::resource('visitors', VisitorController::class);
Route::resource('vaccine-cards', VaccineCardController::class);
Route::get('/report', [ReportController::class, 'index'])->name('report.index');
Route::get('reports/export', [ReportController::class, 'export'])->name('report.export');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Covid Vaccine Info</title>
    <!-- Add Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light " style="background-color: #e35ea9 !important;">
        <a class="navbar-brand" href="{{ url('/')}}" style="color: white;font-weight: bold">Covid Vaccine Info</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('visitors.index') }}" style="font-size: 20px; color: azure; padding: 10px;">Visitors</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('report.index') }}" style="font-size: 20px;color: azure;padding: 10px;">Report</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container mt-4">
        @yield('content')
    </div>

    <!-- Add Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>