routes/web.php
<?php

use App\Http\Controllers\ProvinceController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\VaccineCardController;
use App\Http\Controllers\VisitorController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
   return view('welcome');
});
Route::resource('provinces', ProvinceController::class);
Route::resource('visitors', VisitorController::class);
Route::resource('vaccine-cards', VaccineCardController::class);
Route::get('/report', [ReportController::class, 'index'])->name('report.index');
Route::get('reports/export', [ReportController::class, 'export'])->name('report.export');

app/Models/Visitor.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Visitor extends Model
{
    use HasFactory;
    protected $table = 'visitors';
    protected $fillable = ['province_id', 'doses']; // Add other fillable fields if needed
   

    public function province()
    {
        return $this->belongsTo(Province::class);
    }

    public function vaccineCards()
    {
        return $this->hasMany(VaccineCard::class);
    }
}

app/Http/Controllers/VisitorController.php
<?php

namespace App\Http\Controllers;

use App\Models\Province;
use App\Models\VaccineCard;
use App\Models\Visitor;
use Illuminate\Http\Request;

class VisitorController extends Controller
{
    public function index()
    {
        $visitors = Visitor::with('province')->get();
        // dd($visitors);
        return view('visitors.index', compact('visitors'));
    }

    public function create()
    {
        $provinces = Province::all();
        return view('visitors.create', compact('provinces'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'province_id' => 'required|exists:provinces,id',
            'doses' => 'required|integer|min:1',
        ]);

        Visitor::create($request->all());
        return redirect()->route('visitors.index')
                         ->with('success', 'Visitor created successfully.');
    }

    public function edit(Visitor $visitor)
    {
        $provinces = Province::all();
        return view('visitors.edit', compact('visitor', 'provinces'));
    }

    public function update(Request $request, Visitor $visitor)
    {
        $request->validate([
            'province_id' => 'required|exists:provinces,id',
            'doses' => 'required|integer|min:1',
        ]);

        $visitor->update($request->all());
        return redirect()->route('visitors.index')
                         ->with('success', 'Visitor updated successfully.');
    }

    public function destroy(Visitor $visitor)
    {
        $visitor->delete();
        return redirect()->route('visitors.index')
                         ->with('success', 'Visitor deleted successfully.');
    }
}

resources/views/visitors/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h2>Add Visitor</h2>
    <form action="{{ route('visitors.store') }}" method="POST">
        @csrf
        <div class="form-group">
            <label for="province_id">Province</label>
            <select name="province_id" id="province_id" class="form-control" required>
                @foreach($provinces as $province)
                    <option value="{{ $province->id }}">{{ $province->name }}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="doses">Number of Doses</label>
            <input type="number" name="doses" id="doses" class="form-control" required>
        </div>
        <button type="submit" class="btn btn-primary">Add Visitor</button>
    </form>
</div>
@endsection

resources/views/visitors/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h2>Edit Visitor</h2>
    <form action="{{ route('visitors.update', $visitor->id) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="province_id">Province</label>
            <select name="province_id" id="province_id" class="form-control" required>
                @foreach($provinces as $province)
                    <option value="{{ $province->id }}" {{ $province->id == $visitor->province_id ? 'selected' : '' }}>
                        {{ $province->name }}
                    </option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="doses">Number of Doses</label>
            <input type="number" name="doses" id="doses" class="form-control" value="{{ $visitor->doses }}" required>
        </div>
        <button type="submit" class="btn btn-primary">Update Visitor</button>
    </form>
</div>
@endsection

resources/views/visitors/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <h4>List Visitors</h4>
    @if (session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @endif
    <a href="{{ route('visitors.create') }}" class=" btn btn-primary mb-3 " style="float: inline-end">Add Visitor</a>
    <table  class="table table-hover" style="cursor: pointer">
        <thead class="table-success">
            <tr>
                <th>No</th>
                <th>Province</th>
                <th>Number of Doses</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach($visitors as $index => $visitor)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $visitor->province->name }}</td>
                    <td>{{ $visitor->doses }}</td>
                    {{-- <td>{{ $visitor->visitor_count  }}</td> --}}
                    <td>
                        <a href="{{ route('visitors.edit', $visitor->id) }}" class="btn btn-warning btn-sm">Edit</a>
                        <form action="{{ route('visitors.destroy', $visitor->id) }}" method="POST" style="display:inline-block;">
                            @csrf
                            @method('DELETE')
                            <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('Are you sure?')">Delete</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endsection